### ISSUE TITLE
Форматирование при помощи Prettier

### ISSUE THREAD

**Issue by akuznetsov-md** [CyberDoge/mercury-test-task-react#3]
Из ревью ТЗ при отборе на стажировку:

> Код гораздо лучше читается, когда он отформатирован в едином стиле: отступы, максимальная длина строки, тип кавычек и т.д.
>
> На своих проектах мы используем инструмент Prettier https://prettier.io/
> Попробуй применить этот инструмент в своей работе со стандартной конфигурацией.

**Comment by CyberDoge** [comment]
Я и форматировал с помощью prettier, через WebStorm. Может быть у WebStorm свои дефолтные конфиги Prettier, но я помимо этого запускал форматирование Prettier-ом через консоль

**Comment by akuznetsov-md** [comment]
Возможно, пропустил что-то. Попробуй настроить прекоммит хук, который автоматически будет прогонять файлы через prettier перед коммитом — https://prettier.io/docs/en/precommit.html

Мы всегда так делаем на проектах.

**Comment by CyberDoge** [comment]
Спасибо, удобно. Не подумал, что так можно сделать

**Comment by CyberDoge** [comment]
![image](https://user-images.githubusercontent.com/36932153/66232739-a8388680-e6fa-11e9-9612-c2e5c237c195.png)
Нашел в чем была проблема. WebStorm стояли галочки на форматирование кода перед коммитом
