### ISSUE TITLE
Именование компонентов

### ISSUE THREAD

**Issue by akuznetsov-md** [CyberDoge/mercury-test-task-react#4]
Из документации БЭМ:
> Название блока характеризует смысл («что это?» — «меню»: menu, «кнопка»: button), а не состояние («какой, как выглядит?» — «красный»: red, «большой»: big).

Можно заменить слово "блок" на "компонент" и пользоваться этим правилом. В твоей работе меня смущает название `CentralBlock`

**Comment by CyberDoge** [comment]
CentralBlock - это Центральный блок, что предполагает, что он будет хранить компоненты в центре страницы. В принципе его имя содержит его полную характеристику. Возможно имя не удачное или можно обойтись без него, но мне не приходит в голову идеальных вариантов

**Comment by akuznetsov-md** [comment]
Кроме того, не стоит указывать в названии компонента слово "Block" или "Component". В React все есть компонент, так что это лишнее дублирование информации. Лучше концентрироваться на сути компонента. Если не знать контекста, то можно только догадываться, что делают компоненты Form и Info (FormBlock и InfoBlock в твоем варианте). Их названия стоит конкретизировать

**Comment by akuznetsov-md** [comment]
> CentralBlock - это Центральный блок, что предполагает, что он будет хранить компоненты в центре страницы

"Центральный" — это состояние, характеризующее внешний вид. Стоит концентрироваться на сути, смысле, а не на внешнем виде.

**Comment by akuznetsov-md** [comment]
В html есть тег main для обозначения основного контейнера страницы. Можно особо не выдумывать и взять такое же название

**Comment by CyberDoge** [comment]
Ещё хотел задать вопрос, когда лучше создавать класс, а когда можно функцию? Я привык всегда создавать классы и мне даже так более привычно, но может быть есть какие-то best practices и правила, на которые мне стоит ориентироваться

**Comment by akuznetsov-md** [comment]
Команда разработчиков делает ставку на функциональные компоненты. С появлением хуков уже нельзя сказать, что функциональные компоненты в чем-то уступают по функционалу классам.

Про разницу в производительности мне тоже трудно сказать — лично я не замерял и мне кажется особо больших различий в данный момент нет.

Если говорить о Hot Module Replacement, то непонятно как его делать с компонентами-классами из-за необходимости сохранения состояния. Т.е. в этом пункте как будто бы выигрывают функции (но я не знаю как обстоят дела HMR с хуками).

Если говорить о читаемости кода, то классы мне больше нравятся чем хуки, но потенциально механизм хуков мощнее в плане обработки некоторых корнер-кейсов 

В общем, все ведет к тому, что функции предпочтительнее, но лично я не против классов. Так что пока можешь делать как угодно

Можешь почитать статью Дэна Абрамова на этот счет. Я тоже перечитаю :)
https://overreacted.io/how-are-function-components-different-from-classes/

**Comment by CyberDoge** [comment]
Спасибо, обязательно почитаю
