### ISSUE TITLE
Недостаточная декомпозиция 

### ISSUE THREAD

**Issue by akuznetsov-md** [CyberDoge/mercury-test-task-react#5]
Код стоит выделять в компонент не только по признаку того, что он делает (форма авторизации и профиль профиль пользователя). Компонент это "строительный материал" интерфейсов, позволяющий "собирать" экраны приложений в едином стиле.

Иногда набор таких компонентов называют UI Kit. По сути это такой HTML++, который из коробки красивый.

Например, такой код легко читается, но выглядит плохо.
Стандартный внешний вид html элементов очень далек от того, что мы привыкли видеть в веб приложениях
```
<form>
  <input type="email" placeholder="E-mail" />
  <input type="password" placeholder="Password" />
  <button>Login<button>
</form>
```

React позволяет нам сделать собственный набор элементов, который не будет уступать в читаемости, но исправит внешний вид:
```
<Form>
  <Input type="email" placeholder="E-mail" />
  <Input type="password" placeholder="Password" />
  <Button>Login<Button>
</Form>
```

Компоненты Form, Input и Button — это как раз компоненты, которые можно объединить в UI Kit. С помощью этих же компонентов можно создать, например, форму регистрации и она будет выглядеть в том же стиле.

При создании различных админок для проектов мы часто используем Material UI. Выбирая названия свойств для собственных компонентов или для собственного UI Kit можно ориентироваться на API компонентов Material UI.

https://material-ui.com/ru/components/buttons/

**Comment by CyberDoge** [comment]
Не удаётся грамотно декомпозировать компоненты, чтоб это получилось оправдано и полезно

**Comment by akuznetsov-md** [comment]
Нужно просто набивать руку, чтобы полезность была более наглядна.
